version: '3.9'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec rake bot:listen
    env_file: .env
    depends_on:
      - redis
      - db
    restart: always
    networks:
      - backend

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec sidekiq -r ./config/boot.rb
    env_file: .env
    depends_on:
      - redis
      - db
    restart: always
    networks:
      - backend

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

  postgres:
    image: postgres:15-alpine
    restart: always
    volumes:
      - site_snoop_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: site_snoop
      POSTGRES_USER: snoop
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    networks:
      - backend

volumes:
  site_snoop_pgdata:

networks:
  backend:
